Add mw.Title types
wikimedia/typescript-types pull request #10
Opened 2021-07-19 04:07 UTC by jdlrobson

2021-07-20 02:42 UTC, DannyS712 requested changes

2021-07-20 02:42 UTC, DannyS712 commented on MediaWiki.d.ts
> +	getUrl(): string
getUrl takes an optional object parameter

We should also be consistent one way or the other about the capitalization of "number" or "Number" - its fine to add whichever one you want in this patch, but afterwards we should standardize

2021-07-20 02:42 UTC, DannyS712 commented on MediaWiki.d.ts
> +	requestIdleCallback( callback: Function ): () => void,
Should be included in commit message

2021-07-20 20:42 UTC, jdlrobson commented on MediaWiki.d.ts
> +	getUrl(): string
Done. Noted about number vs Number. I think "number" is definitely the right choice considering over repos.

2021-07-20 20:42 UTC, jdlrobson commented on MediaWiki.d.ts
> +	requestIdleCallback( callback: Function ): () => void,
Done.

2021-07-21 17:43 UTC, DannyS712 commented on MediaWiki.d.ts
> +	requestIdleCallback( callback: Function ): () => void,
The overall title for this is still "Add mw.Title types"

2021-07-21 17:43 UTC, DannyS712 commented on MediaWiki.d.ts
> +	requestIdleCallback( callback: Function ): () => void
shouldn't this still have a comma afterwards?

2021-07-21 18:04 UTC, jdlrobson commented on MediaWiki.d.ts
> +	requestIdleCallback( callback: Function ): () => void,
I'm confused. I'm not touching this line any more. requestIdleCallback has nothing to do with mw.Title types.

2021-07-21 18:04 UTC, jdlrobson commented on MediaWiki.d.ts
> +	requestIdleCallback( callback: Function ): () => void
I'm a bit confused about your early change. I thought you were asking for me to move the definition.

Note this line is not being touched as part of this change as it's unrelated.

2021-07-21 18:07 UTC, DannyS712 commented on MediaWiki.d.ts
> +	requestIdleCallback( callback: Function ): () => void,
Oh - I guess I'm confused by the github interface, I thought it was still be included in the overall change

2021-07-21 18:08 UTC, DannyS712 commented on MediaWiki.d.ts
> +	requestIdleCallback( callback: Function ): () => void
Sorry, ignore me, I got confused by the github interface

2021-07-21 22:04 UTC, merged