mw.msg can take multiple parameters
wikimedia/typescript-types pull request #11
Opened 2021-07-19 04:08 UTC by jdlrobson

e.g mw.msg( 'key', 'Argument 1, 'Argument 2')

2021-07-19 04:10 UTC, jdlrobson commented
@DannyS712 - can you sanity check this pull request and the other three for me? Thanks in advance.

2021-07-20 02:44 UTC, DannyS712 requested changes

2021-07-20 02:44 UTC, DannyS712 commented on MediaWiki.d.ts
> +	msg( messageName: string|null, ...args: string[] ): string;
should have @param documentation, and its not just strings (core documents it as `{...Mixed}`)

2021-07-21 22:35 UTC, jdlrobson commented on MediaWiki.d.ts
> +	msg( messageName: string|null, ...args: string[] ): string;
Done.

2021-07-23 04:56 UTC, DannyS712 commented on MediaWiki.d.ts
> +	msg( messageName: string|null, ...args: string[] ): string;
If I go to https://github.com/wikimedia/typescript-types/pull/11/files its still missing the @param - am I missing something?

2021-07-23 15:06 UTC, jdlrobson commented on MediaWiki.d.ts
> +	msg( messageName: string|null, ...args: string[] ): string;
Nope I just forgot to commit :)

2021-07-23 17:27 UTC, merged