mw.config returns type any
wikimedia/typescript-types pull request #8
Opened 2021-07-19 04:06 UTC by jdlrobson

2021-07-20 02:37 UTC, DannyS712 requested changes
(github won't let me leave an inline comment on the line since its not a part of the patch, so putting here) the same applies to mw.user.options because that also uses a `Map` object to store things, and that should also be updated to return any - or maybe instead of duplicating the documentation we should create a `Map` interface object that both of them use. -1

2021-07-21 22:33 UTC, jdlrobson commented
> (github won't let me leave an inline comment on the line since its not a part of the patch, so putting here) the same applies to mw.user.options because that also uses a `Map` object to store things, and that should also be updated to return any - or maybe instead of duplicating the documentation we should create a `Map` interface object that both of them use. -1

Good idea. Done!

2021-07-23 04:55 UTC, DannyS712 reviewed
Suggest changing commit message to be "Add and use mw.Map interface" or similar since this isn't just about mw.config anymore

2021-07-23 04:55 UTC, DannyS712 commented on MediaWiki.d.ts
> +interface MwMap {
we can also add this as a direct part of the MediaWiki interface, available as `mw.Map` client side.

2021-07-23 15:06 UTC, jdlrobson commented on MediaWiki.d.ts
> +interface MwMap {
Done.

2021-07-23 15:07 UTC, jdlrobson commented
> Suggest changing commit message to be "Add and use mw.Map interface" or similar since this isn't just about mw.config anymore

Yeh I do that on merge in Githubs workflow.

2021-07-23 15:57 UTC, merged