Add API methods
wikimedia/typescript-types pull request #9
Opened 2021-07-19 04:07 UTC by jdlrobson

2021-07-20 02:39 UTC, DannyS712 requested changes

2021-07-20 02:39 UTC, DannyS712 commented on MediaWiki.d.ts
> +	postWithToken( token: string, params: Object, ajaxOptions?: Object ): JQuery.Promise<any>;
I suggest using the same variable names as the actual mw.api code uses, but at the very least `token` should be `tokenType` because we don't actually pass the token, but rather the name/type of which token to use, and that is unclear from this documentation

2021-07-20 20:38 UTC, jdlrobson commented on MediaWiki.d.ts
> +	postWithToken( token: string, params: Object, ajaxOptions?: Object ): JQuery.Promise<any>;
Done.

2021-07-21 17:42 UTC, DannyS712 approved these changes

2021-07-21 18:03 UTC, merged